
Config['vehicletrunk'] = {
    limit = 25,
    default = 5,

    NoTrunkVehicles = {},
    bypassVehicles = {``},
    bypassClass = {10, 11, 12, 15, 20},

    limits = {
        [0] = 40, --Compact
        [1] = 50, --Sedan
        [2] = 80, --SUV
        [3] = 50, --Coupes
        [4] = 70, --Muscle
        [5] = 40, --Sports Classics
        [6] = 45, --Sports
        [7] = 45, --Super
        [8] = 15, --Motorcycles
        [9] = 130, --Off-road
        [10] = 300, --Industrial
        [11] = 100, --Utility
        [12] = 110, --Vans
        [13] = 0, --Cycles
        [14] = 155, --Boats
        [15] = 120, --Helicopters
        [16] = 800, --Planes
        [17] = 40, --Service
        [18] = 40, --Emergency
        [19] = 0, --Military
        [20] = 300, --Commercial
        [21] = 0 --Trains
    },

    weapons = {
        WEAPON_KNIFE = 0.1, --Couteau
        WEAPON_KNUCKLE = 0.1, --Poing Americain
        WEAPON_NIGHTSTICK = 0.2, --Mattraque
        WEAPON_HAMMER = 0.3, --Marteau
        WEAPON_BAT = 0.3, --Bat de Baseball
        WEAPON_GOLFCLUB = 0.2, --Bat de Golf
        WEAPON_CROWBAR = 0.2, --Pied de Biche
        WEAPON_BOTTLE = 0.1, --Bouteille Cassé
        WEAPON_DAGGER = 0.1, --Couteau Dagger
        WEAPON_HATCHET = 0.3, --Hachette
        WEAPON_MACHETE = 0.3, --Machette
        WEAPON_FLASHLIGHT = 0.1, --Lampe torche
        WEAPON_SWITCHBLADE = 0.1, --Cran d'Arrêt
        WEAPON_BZGAS = 0.5, --Grenade Lacrymogène
        WEAPON_SMOKEGRENADE = 0.5, --Grenade Fumigène
        WEAPON_MOLOTOV = 0.5, --Cocktel Molotov
        WEAPON_FIREEXTINGUISHER = 2.0, --Extincteur
        WEAPON_PETROLCAN = 10.0, --Bidon d'Essence
        WEAPON_FLARE = 0.5, --Fusée eclairante
        WEAPON_BALL = 0.5, --Balle
        WEAPON_REVOLVER = 1.0, --Revolver
        WEAPON_REVOLVER_MK2 = 1.0, --Revolver MK2
        WEAPON_POOLCUE = 0.2, --Barre de Billard
        WEAPON_WRENCH = 0.3, --Clef a Molette
        WEAPON_PISTOL = 1.0, --Pistolet
        WEAPON_COMBATPISTOL = 1.0, --Pitolet Combat
        WEAPON_PISTOL50 = 1.0, --Desert Eaglel
        WEAPON_SNSPISTOL = 1.0, --Petoire
        WEAPON_HEAVYPISTOL = 1.0, --Pistolet Lourd
        WEAPON_VINTAGEPISTOL = 1.5, --Pistolet Vintage
        WEAPON_STUNGUN = 1.0, --Taser
        WEAPON_FLAREGUN = 0.5, --Fusee de Detresse
        WEAPON_MARKSMANPISTOL = 1.5, --Pistol Fusil Court
        WEAPON_MICROSMG = 2.3, --UZI
        WEAPON_MINISMG = 2.3, --Scorpion
        WEAPON_SMG = 3.0, --SMG MP5
        WEAPON_ASSAULTSMG = 3.0, --P90
        WEAPON_MG = 7.5, --MG bateuse
        WEAPON_COMBATMG = 7.5, --Mitrailleuse de Combat
        WEAPON_COMBATPDW = 3.0, --SMG PDW
        WEAPON_GUSENBERG = 7.5, --Mitrailleuse Camembere Gangster
        WEAPON_MACHINEPISTOL = 2.3, --Pistolet Mitrailleur Leger
        WEAPON_ASSAULTRIFLE = 3.5, --AK 47
        WEAPON_CARBINERIFLE = 3.5, --Carabine
        WEAPON_ADVANCEDRIFLE = 3.5, --Advanced Assault
        WEAPON_SPECIALCARBINE = 3.5, --Carabine Spéciale
        WEAPON_BULLPUPRIFLE = 3.5, --Assault BullUp
        WEAPON_COMPACTRIFLE = 2.5, --Mini AK47U
        WEAPON_PUMPSHOTGUN = 3.2, --Fusil a Pompe
        WEAPON_SAWNOFFSHOTGUN = 3.2, --Pompe Canon scier
        WEAPON_MUSKET = 3.0, --Musket de Chasse
        WEAPON_DBSHOTGUN = 3.2, --Pompe double canon/coup
        WEAPON_SNIPERRIFLE = 10.0, --Sniper Rifle
        WEAPON_HEAVYSNIPER = 10.0, --Sniper Lourd
        WEAPON_DOUBLEACTION = 2.0, --revolver Red Dead
        WEAPON_GADGETPISTOL = 1.5, --Pistolet de Cayo
        WEAPON_RPG = 3.5, --Lance Rocket
        WEAPON_BATTLEAXE = 0.3, --Hache de Combat
        WEAPON_STONE_HATCHET = 0.3, --Hache en Pierre
        WEAPON_PISTOL_MK2 = 1.0, --Pistolet MK2
        WEAPON_APPISTOL = 1.0, --Pistolet Automatique
        WEAPON_SNSPISTOL_MK2 = 1.0, --Petoire MK2
        WEAPON_CERAMICPISTOL = 1.0, --Pistolet en Céramique
        WEAPON_NAVYREVOLVER = 1.0, --Revolver de la Marine
        WEAPON_SMG_MK2 = 3.0, --SMG MP5 MK2
        WEAPON_PUMPSHOTGUN_MK2 = 3.2, --Fusil a Pompe MK2
        WEAPON_ASSAULTSHOTGUN = 4.0, --Fusil a Pompe d'Assault
        WEAPON_BULLPUPSHOTGUN = 4.0, --Fusil a Pompe Bullpup 
        WEAPON_HEAVYSHOTGUN = 4.0, --Fusil a Pompe Lourd
        WEAPON_AUTOSHOTGUN = 4.0, --Fusil a Pompe Automatique
        WEAPON_COMBATSHOTGUN = 4.0, --Fusil a Pompe de Combat
        WEAPON_ASSAULTRIFLE_MK2 = 3.5, --AK 47 MK2
        WEAPON_CARBINERIFLE_MK2 = 3.5, --Carabine MK2
        WEAPON_SPECIALCARBINE_MK2 = 3.5, --Carabine Spéciale MK2
        WEAPON_BULLPUPRIFLE_MK2 = 3.5, --Assault BullUp MK2
        WEAPON_MILITARYRIFLE = 3.5, --Fusil d'Assault de Cayo
        WEAPON_HEAVYRIFLE = 3.5, --Fusi d'Assault Lourd
        WEAPON_TACTICALRIFLE = 3.5, --Fusi d'Assault Tactique
        WEAPON_COMBATMG_MK2 = 7.5, --Mitrailleuse de Combat MK2
        WEAPON_HEAVYSNIPER_MK2 = 10.0, --Sniper Lourd MK2
        WEAPON_MARKSMANRIFLE = 10.0, --Sniper 
        WEAPON_MARKSMANRIFLE_MK2 = 10.0, --Sniper MK2
        WEAPON_PRECISIONRIFLE = 10.0, --Sniper de Précision
        WEAPON_GRENADELAUNCHER = 8.0, --Lance Grenade
        WEAPON_GRENADELAUNCHER_SMOKE = 8.0, --Lance Fumigène
        WEAPON_MINIGUN = 8.0, --Minigun
        WEAPON_FIREEXTINGUISHER = 3.5, --Lanceur Pyrotechnique
        WEAPON_HOMINGLAUNCHER = 3.5, --Lance Missile
        WEAPON_COMPACTLAUNCHER = 3.5, --Lance Grenade Compact
        WEAPON_GRENADE = 0.2, --Grenade
        WEAPON_STICKYBOMB = 0.2, --Bombe Colante
        WEAPON_PROXMINE = 0.2, --Mine de Proximité
        WEAPON_SNOWBALL = 0.1, --Boule de Neige
        WEAPON_PIPEBOMB = 0.1, --Bombe Artisanale
        GADGET_PARACHUTE = 0.5 --Parachute
    }
}