Config['boutique'] = {
    ItemSpawn = vector3(965, 42.1, 123.2),
    CamCoords = vector3(961.1, 48.4, 124.5),
    
    Categories = {
     { name = "cars", label = "~p~ Véhicules", description = nil },
     { name = "armes_exclu", label = "~r~ Armes ~y~[Exclusives]", description = nil },
     { name = "armes_assaults", label = "~r~ Armes ~g~[Assaults]", description = nil },
     { name = "armes_pistols", label = "~r~ Armes ~g~[Pistolets]", description = nil },
     { name = "armes_snipers", label = "~r~ Armes ~g~[Snipers]", description = nil },
     { name = "armes_pompes", label = "~r~ Armes ~g~[Fusils A Pompes]", description = nil },
     { name = "armes_meles", label = "~r~ Armes ~g~[Meles]", description = nil },
    },

    Items = {
     ['cars'] = {
        -- NEWS --
        { model = '17mansorypnmr',       label = "Mansory 17",     price = 3000},
        { model = '21sierra',            label = "Sierra 21",      price = 3000},
        { model = '911gtrs',             label = "911 GTRS",       price = 3000},
        { model = 'amrevu23mg',          label = "AMG 23",         price = 3000},
        { model = 'cayen19',             label = "Cayen",          price = 3000},
        { model = 'centuria',            label = "Centuria",       price = 5000},
        { model = 'chironsuper',         label = "Chiron",         price = 5000},
        { model = 'evo9',                label = "Evo 9",          price = 3000},
        { model = 'evoss',               label = "Evoss",          price = 5000},
        { model = 'fpaceprior',          label = "Jagar Prior",    price = 3000},
        { model = 'GODzDRIFTCAT',        label = "Degde",          price = 3000},
        { model = 'gta5rp_veh_c63s',     label = "C63S",           price = 5000},
        { model = 'gta5rp_veh_ferero19', label = "Ferero 19",      price = 3000},
        { model = 'gta5rp_veh_gle1',     label = "GLE",            price = 5000},
        { model = 'gta5rp_veh_gtr33',    label = "GTR 33",         price = 3000},
        { model = 'oycdefender',         label = "Defender",       price = 3000},
        { model = 'rmodr50',             label = "R50",            price = 3000},
        { model = 'rmodsvj',             label = "SVJ",            price = 5000},
        { model = 'rs7',                 label = "RS7",             price = 3000},
        { model = 's1',                  label = "S1",             price = 3000},
        { model = 'terzo1',              label = "Terzec",         price = 3000},
        { model = 'mansrs6',             label = "R6 Mont Souris", price = 5000},
        { model = 'GODzZEE28WB',         label = "WB",             price = 5000},
        { model = 'GODzBABYTREXSUELO',   label = "Ram",            price = 3000},
        { model = 'vnmpuro',             label = "Feraro",         price = 6000},
        { model = 'm4gts',               label = "M4Gts",          price = 6000},
        { model = 'pxxbk',               label = "pxxbk",         price = 6000},
        { model = 'tw_ar3sb',               label = "Odi RS33 SportBack 2022",         price = 6000},
        { model = 'rs7abt',               label = "Odi RS77 R ABB",         price = 6000},
        { model = 'rsq8pxx',               label = "Odi RSQ88 widebody",         price = 6000},
        { model = 's500',               label = "mercedouze 63s amg s633",         price = 6000},

        { model = 'tmax560tech',               label = "TMIN 560",         price = 4000},
        { model = '2020g900',               label = "Brabous G900",         price = 5000},
        { model = 'drewideamg',               label = "AMG GTR Widebody",         price = 5500},
        { model = 'e63sw212',               label = "mercedouze Benz E63 S AMG",         price = 6000},


     },
     ['armes_exclu'] = {
        { model = 'vandalex',          weaponName = 'WEAPON_VANDALEX',          label = "VandalEx",             price = 6500},
        { model = 'menace',            weaponName = 'WEAPON_MENACE',            label = "Menace",               price = 6500},
     },
     ['armes_assaults'] = {
        { model = 'w_ar_carbinerifle2', weaponName = 'WEAPON_CARBINERIFLE2', label = "Carabine Spécial Redskin", price = 6000},
        { model = 'w_ar_carbinerifle3', weaponName = 'WEAPON_CARBINERIFLE3', label = "Carabine Spécial Redskin 2", price = 6000},
        { model = 'w_ar_carbinerifle4', weaponName = 'WEAPON_CARBINERIFLE4', label = "Carabine Spécial Redskin 3", price = 6000},
        { model = 'w_ar_carbinerifle5', weaponName = 'WEAPON_CARBINERIFLE5', label = "Carabine Spécial Redskin 4", price = 6000},
        { model = 'w_ar_carbinerifle6', weaponName = 'WEAPON_CARBINERIFLE6', label = "Carabine Spécial Redskin 5", price = 6000},
        { model = 'w_ar_carbinerifle7', weaponName = 'WEAPON_CARBINERIFLE7', label = "Carabine Spécial Redskin 6", price = 6000},
        { model = 'w_ar_animem4', weaponName = 'WEAPON_ANIMEM4', label = "M4", price = 6000},
        { model = 'w_ar_specialcarbine2mk2', weaponName = 'WEAPON_SPECIALCARBINE2_MK2', label = "Carabine Spécial MK2", price = 6000},
        { model = 'w_ar_specialcarbine2', weaponName = 'WEAPON_SPECIALCARBINE2', label = "Carabine Spécial Reskin", price = 6000},
        { model = 'w_ar_specialcarbine3', weaponName = 'WEAPON_SPECIALCARBINE3', label = "Carabine Spécial Reskin 2", price = 6000},
        { model = 'w_ar_a15rc', weaponName = 'WEAPON_A15RC', label = "A15RC", price = 6000},
        { model = 'w_ar_neva', weaponName = 'WEAPON_NEVA', label = "NEVA", price = 6000},
        { model = 'w_ar_iar', weaponName = 'WEAPON_IAR', label = "IAR", price = 6000},
        { model = 'w_ar_m133', weaponName = 'WEAPON_M133', label = "M133", price = 6000},
        { model = 'w_ar_jrbak', weaponName = 'WEAPON_JRBAK', label = "JRBAK", price = 6000},
        { model = 'w_ar_famasu1', weaponName = 'WEAPON_FAMASU1', label = "FAMASU1", price = 6000},
        { model = 'w_ar_grau', weaponName = 'WEAPON_GRAU', label = "GRAU", price = 6000},
        { model = 'w_ar_ak47s', weaponName = 'WEAPON_AK47S', label = "AK47S", price = 6000},
        { model = 'w_ar_sr47', weaponName = 'WEAPON_SR47', label = "SR47", price = 6000},
        { model = 'w_ar_ak4k', weaponName = 'WEAPON_AK4K', label = "AK4K", price = 6000},
        { model = 'w_ar_akmkh', weaponName = 'WEAPON_AKMKH', label = "AKMKH", price = 6000},
        { model = 'w_ar_bulldog', weaponName = 'WEAPON_BULLDOG', label = "BULLDOG", price = 6000},
        { model = 'w_ar_casr', weaponName = 'WEAPON_CASR', label = "CASR", price = 6000},
        { model = 'w_ar_drh', weaponName = 'WEAPON_DRH', label = "DRH", price = 6000},
        { model = 'w_ar_fmr', weaponName = 'WEAPON_FMR', label = "FMR", price = 6000},
        { model = 'w_ar_fn42', weaponName = 'WEAPON_FN42', label = "FN42", price = 6000},
        { model = 'w_ar_galilar', weaponName = 'WEAPON_GALILAR', label = "GALILAR", price = 6000},
        { model = 'w_ar_m16a3', weaponName = 'WEAPON_M16A3', label = "M16A3", price = 6000},
        { model = 'w_ar_slr15', weaponName = 'WEAPON_SLR15', label = "SLR15", price = 6000},
        { model = 'w_ar_arc15', weaponName = 'WEAPON_ARC15', label = "ARC15", price = 6000},
        { model = 'w_ar_ars', weaponName = 'WEAPON_ARS', label = "ARS", price = 6000},
        { model = 'w_ar_howa_2', weaponName = 'WEAPON_HOWA_2', label = "HOWA_2", price = 6000},
        { model = 'w_ar_mza', weaponName = 'WEAPON_MZA', label = "MZA", price = 6000},
        { model = 'w_ar_safak', weaponName = 'WEAPON_SAFAK', label = "SAFAK", price = 6000},
        { model = 'w_ar_sar', weaponName = 'WEAPON_SAR', label = "SAR", price = 6000},
        { model = 'w_ar_sfak', weaponName = 'WEAPON_SFAK', label = "SFAK", price = 6000},
        { model = 'w_ar_arma1', weaponName = 'WEAPON_ARMA1', label = "ARMA1", price = 6000},
        { model = 'w_ar_g36', weaponName = 'WEAPON_G36', label = "G36", price = 6000},
        { model = 'w_ar_lr300', weaponName = 'WEAPON_LR300', label = "LR300", price = 6000},
        { model = 'w_ar_m416p', weaponName = 'WEAPON_M416P', label = "M416P", price = 6000},
        { model = 'w_ar_nanite', weaponName = 'WEAPON_NANITE', label = "NANITE", price = 6000},
        { model = 'w_ar_sf2', weaponName = 'WEAPON_SF2', label = "SF2", price = 6000},
        { model = 'w_ar_sfrifle', weaponName = 'WEAPON_SFRIFLE', label = "SFRIFLE", price = 6000},
        { model = 'w_ar_cfs', weaponName = 'WEAPON_CFS', label = "CFS", price = 6000},
        { model = 'w_ar_ak47', weaponName = 'WEAPON_AK47', label = "AK47", price = 6000},
        { model = 'w_ar_aug', weaponName = 'WEAPON_AUG', label = "AUG", price = 6000},
        { model = 'w_ar_sunda', weaponName = 'WEAPON_SUNDA', label = "SUNDA", price = 6000},
        { model = 'w_ar_g3_2', weaponName = 'WEAPON_G3_2', label = "G3_2", price = 6000},
        { model = 'w_ar_groza', weaponName = 'WEAPON_GROZA', label = "GROZA", price = 6000},
        { model = 'w_ar_acr', weaponName = 'WEAPON_ACR', label = "ACR", price = 6000},
        { model = 'w_ar_acwr', weaponName = 'WEAPON_ACWR', label = "ACWR", price = 6000},
        { model = 'w_ar_anarchy', weaponName = 'WEAPON_ANARCHY', label = "ANARCHY", price = 6000},
        { model = 'w_ar_far', weaponName = 'WEAPON_FAR', label = "FAR", price = 6000},
        { model = 'w_ar_gk47', weaponName = 'WEAPON_GK47', label = "GK47", price = 6000},
        { model = 'w_ar_tar21', weaponName = 'WEAPON_TAR21', label = "TAR21", price = 6000},
        { model = 'w_ar_akpu', weaponName = 'WEAPON_AKPU', label = "AKPU", price = 6000},
        { model = 'w_ar_an94', weaponName = 'WEAPON_AN94_2', label = "AN94_2", price = 6000},
        { model = 'w_ar_art64', weaponName = 'WEAPON_ART64', label = "ART64", price = 6000},
        { model = 'w_ar_gys', weaponName = 'WEAPON_GYS', label = "GYS", price = 6000},
        { model = 'w_ar_sm237', weaponName = 'WEAPON_SM237', label = "SM237", price = 6000},
        { model = 'w_ar_ss2_2', weaponName = 'WEAPON_SS2_2', label = "SS2_2", price = 6000},
        { model = 'w_ar_scarsc', weaponName = 'WEAPON_SCARSC', label = "SCARSC", price = 6000},
        { model = 'w_ar_va030', weaponName = 'WEAPON_VA030', label = "VA030", price = 6000},
        { model = 'w_ar_ar121', weaponName = 'WEAPON_AR121', label = "AR121", price = 6000},
        { model = 'w_ar_lgwii', weaponName = 'WEAPON_LGWII', label = "Lewis Gun WWII", price = 6000},
        { model = 'w_ar_ar727', weaponName = 'WEAPON_AR727', label = "AR727", price = 6000},
        { model = 'w_ar_anr15', weaponName = 'WEAPON_ANR15', label = "ANR15", price = 6000},
        { model = 'w_ar_dks501', weaponName = 'WEAPON_DKS501', label = "DKS501", price = 6000},
        { model = 'w_ar_scifw', weaponName = 'WEAPON_SCIFW', label = "SCIFW", price = 6000},
        { model = 'w_ar_ssr56', weaponName = 'WEAPON_SSR56', label = "SSR56", price = 6000},
        { model = 'w_ar_akbg', weaponName = 'WEAPON_AKBG', label = "AKBG", price = 6000},
        { model = 'w_ar_anm4', weaponName = 'WEAPON_ANM4', label = "ANM4", price = 6000},
        { model = 'w_ar_gvandal', weaponName = 'WEAPON_GVANDAL', label = "GVANDAL", price = 6000},
        { model = 'w_ar_l85', weaponName = 'WEAPON_L85', label = "L85", price = 6000},
        { model = 'w_ar_limpid', weaponName = 'WEAPON_LIMPID', label = "LIMPID", price = 6000},
        { model = 'w_ar_truvelo', weaponName = 'WEAPON_TRUVELO', label = "TRUVELO", price = 6000},
        { model = 'w_ar_akmk01', weaponName = 'WEAPON_AKMK01',    label = "AKMK01",    price = 6000},
        { model = 'w_sb_sb4s', weaponName = 'WEAPON_SB4S', label = "SB4S", price = 6000},
        { model = 'w_sb_h2smg', weaponName = 'WEAPON_H2SMG', label = "H2SMG", price = 6000},
        { model = 'w_sb_hfsmg', weaponName = 'WEAPON_HFSMG', label = "HFSMG", price = 6000},
        { model = 'w_sb_ms32', weaponName = 'WEAPON_MS32', label = "MS32", price = 6000},
        { model = 'w_sb_sarb', weaponName = 'WEAPON_SARB', label = "SARB", price = 6000},
        { model = 'w_sb_ue4', weaponName = 'WEAPON_UE4', label = "UE4", price = 6000},
        { model = 'w_sb_uzi', weaponName = 'WEAPON_UZI', label = "UZI", price = 6000},
        { model = 'w_sb_idw', weaponName = 'WEAPON_IDW', label = "IDW", price = 6000},
        { model = 'w_sb_heavysmg', weaponName = 'WEAPON_HEAVYSMG', label = "HEAVYSMG", price = 6000},
        { model = 'w_sb_smg9', weaponName = 'WEAPON_SMG9', label = "SMG9", price = 6000},
        { model = 'w_sb_r99', weaponName = 'WEAPON_R99', label = "R99", price = 6000},
        { model = 'w_sb_sb181', weaponName = 'WEAPON_SB181', label = "SB181", price = 6000},
        { model = 'w_sb_ump45', weaponName = 'WEAPON_UMP45', label = "UMP45", price = 6000},
        { model = 'w_sb_smg1311', weaponName = 'WEAPON_SMG1311', label = "SMG1311", price = 6000},
        { model = 'w_sb_autosmg', weaponName = 'WEAPON_AUTOSMG', label = "AUTOSMG", price = 6000},
        { model = 'w_sb_mx4', weaponName = 'WEAPON_MX4', label = "MX4", price = 6000},
        { model = 'w_sb_pasmg', weaponName = 'WEAPON_PASMG', label = "PASMG", price = 6000},
     },
     ['armes_pistols'] = {
        { model = 'w_pi_scorpion', weaponName = 'WEAPON_SCORPION', label = "Revolver Scorpion", price = 4000},
        { model = 'w_pi_fn502', weaponName = 'WEAPON_FN502', label = "FN502", price = 4000},
        { model = 'w_pi_hfap', weaponName = 'WEAPON_HFAP', label = "HFAP", price = 4000},
        { model = 'w_pi_knr', weaponName = 'WEAPON_KNR', label = "KNR", price = 4000},
        { model = 'w_pi_cz75', weaponName = 'WEAPON_CZ75', label = "CZ75", price = 4000},
        { model = 'w_pi_pl14', weaponName = 'WEAPON_PL14', label = "PL14", price = 4000},  
        { model = 'w_pi_pistolwhite', weaponName = 'WEAPON_PISTOLWHITE', label = "Pistolet White", price = 4000},  
        { model = 'w_pi_pistolblack', weaponName = 'WEAPON_PISTOLBLACK', label = "Pistolet Black", price = 4000},  
        { model = 'w_pi_pistolpoka', weaponName = 'WEAPON_PISTOLPOKA', label = "Pistolet Poka", price = 4000}, 
        { model = 'w_pi_pistolcalibre50', weaponName = 'WEAPON_PISTOLCALIBRE50', label = "Pistolet Custom 50", price = 4000},  
        { model = 'w_pi_kertus', weaponName = 'WEAPON_KERTUS', label = "Kertus", price = 4000},  
     },
     ['armes_snipers'] = {
        { model = 'w_sr_rgxoperator', weaponName = 'WEAPON_RGXOPERATOR', label = "RGX Operator", price = 5000},
        { model = 'w_sr_marksmanrifle2', weaponName = 'WEAPON_MARKSMANRIFLE2', label = "Sniper Reskin", price = 5000},
        { model = 'w_sr_awp', weaponName = 'WEAPON_AWP', label = "AWP", price = 5000},
        { model = 'w_sr_ditdg', weaponName = 'WEAPON_DITDG', label = "DITDG", price = 5000},
        { model = 'w_sr_m82', weaponName = 'WEAPON_M82', label = "M82", price = 5000},
        { model = 'w_sr_awpmk02', weaponName = 'WEAPON_AWPMK02', label = "AWP MK02", price = 4500},
     },
     ['armes_pompes'] = {
        { model = 'w_sg_m90s', weaponName = 'WEAPON_M90S', label = "M90S", price = 4750},
        { model = 'w_sg_dcs', weaponName = 'WEAPON_DCS', label = "DCS", price = 4750},
        { model = 'w_sg_owshotgun', weaponName = 'WEAPON_OWSHOTGUN', label = "OWSHOTGUN", price = 4750},
        { model = 'w_sg_benellim4', weaponName = 'WEAPON_BENELLIM4', label = "BENELLIM4", price = 4750},
     },
     ['armes_meles'] = {
        { model = 'w_me_katana', weaponName = 'WEAPON_KATANA2', label = "Katana", price = 1500},
        { model = 'w_me_spikedclub', weaponName = 'WEAPON_SPIKEDCLUB', label = "Spiked Club", price = 1500},
        { model = 'w_me_knife_01', weaponName = 'WEAPON_KNIFE2', label = "Couteau", price = 1500},
     },
    },


    Caisses = {
        { img = 'caisse_gold', name = 'gold', label = "Caisse Mystère ~y~Gold", price = 2000, infos = "Vous pouvez gagner: \n- ~p~1 véhicule Classique~s~ \n- ~g~une somme d'argent~s~ \n- ~r~une arme de point (NON PERM)~s~ \nLe lot est tiré au hasard !", gains = {
            { type = 'vehicle', name = 'sultanrs', label = "Sultan RS", chance = 20 },
            { type = 'weapon', name = 'WEAPON_KNIFE', label = "Couteau", chance = 25},
            { type = 'weapon', name = 'WEAPON_BAT', label = "Batte de BaseBall", chance = 25},
            { type = 'weapon', name = 'WEAPON_HATCHET', label = "Hachette", chance = 25},
            { type = 'weapon', name = 'WEAPON_MACHETE', label = "Machette", chance = 25},
            { type = 'weapon', name = 'WEAPON_DAGGER', label = "Poignard", chance = 25},
            { type = 'money', name = '20000', label = "20 000$", chance = 35}
        }},
        { img = 'caisse_diamond', name = 'diamond', label = "Caisse Mystère ~b~Diamond", price = 3000, infos = "Vous pouvez gagner: \n- ~p~1 véhicule Boutique~s~ \n- ~g~une somme d'argent~s~ \n- ~r~une arme (PERMANENTE)~s~ \n- des coins \nLe lot est tiré au hasard !", gains = {
            { type = 'weapon', name = 'WEAPON_KATANA2', label = "Katana", chance = 25},
            { type = 'money', name = '75000', label = "75 000$", chance = 55 },
            { type = 'weapon', name = 'WEAPON_KNIFE2', label = "Couteau", chance = 55 },
        }},

        { img = 'caisse_legendary', name = 'legendary', label = "Caisse Mystère ~r~Légendaire", price = 4000, infos = "Vous pouvez gagner: \n- ~g~une somme d'argent~s~ \n- ~r~une arme RARE (PERMANENTE)~s~ \nLe lot est tiré au hasard !", gains = {
            { type = 'weapon', name = 'WEAPON_KATANA2', label = "Katana", chance = 60},
            { type = 'weapon', name = 'WEAPON_SPIKEDCLUB', label = "SpikedClub", chance = 50},
            { type = 'weapon', name = 'WEAPON_CARBINERIFLE2', label = "Carabine RedSkin 1", chance = 30},
            { type = 'weapon', name = 'WEAPON_CARBINERIFLE4', label = "Carabine RedSkin 3", chance = 30},
            { type = 'money', name = '100000', label = "100 000$", chance = 35},
            { type = 'money', name = '150000', label = "150 000$", chance = 25},
        }}
    }
 }