
local areaCleared = {
	{coords = vector3(1620.0, 1115.0, 80.0), radius = 100.0},
	{coords = vector3(-2480.0, -210.0, 20.0), radius = 100.0}
}

CreateThread(function()
	SetGarbageTrucks(0)
	SetRandomBoats(0)
	SetRandomTrains(0)

	SetRelationshipBetweenGroups(1, `COP`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `MEDIC`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `FIREMAN`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `GANG_1`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `GANG_2`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `GANG_9`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `GANG_10`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_LOST`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MEXICAN`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_FAMILY`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_BALLAS`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_MARABUNTE`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_CULT`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_SALVA`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_WEICHENG`, `PLAYER`)
	SetRelationshipBetweenGroups(1, `AMBIENT_GANG_HILLBILLY`, `PLAYER`)

	local scenarios = {
		'WORLD_VEHICLE_ATTRACTOR',
		'WORLD_VEHICLE_AMBULANCE',
		'WORLD_VEHICLE_BICYCLE_BMX',
		'WORLD_VEHICLE_BICYCLE_BMX_BALLAS',
		'WORLD_VEHICLE_BICYCLE_BMX_FAMILY',
		'WORLD_VEHICLE_BICYCLE_BMX_HARMONY',
		'WORLD_VEHICLE_BICYCLE_BMX_VAGOS',
		'WORLD_VEHICLE_BICYCLE_MOUNTAIN',
		'WORLD_VEHICLE_BICYCLE_ROAD',
		'WORLD_VEHICLE_BIKE_OFF_ROAD_RACE',
		'WORLD_VEHICLE_BIKER',
		'WORLD_VEHICLE_BOAT_IDLE',
		'WORLD_VEHICLE_BOAT_IDLE_ALAMO',
		'WORLD_VEHICLE_BOAT_IDLE_MARQUIS',
		'WORLD_VEHICLE_BOAT_IDLE_MARQUIS',
		'WORLD_VEHICLE_BROKEN_DOWN',
		'WORLD_VEHICLE_BUSINESSMEN',
		'WORLD_VEHICLE_HELI_LIFEGUARD',
		'WORLD_VEHICLE_CLUCKIN_BELL_TRAILER',
		'WORLD_VEHICLE_CONSTRUCTION_SOLO',
		'WORLD_VEHICLE_CONSTRUCTION_PASSENGERS',
		'WORLD_VEHICLE_DRIVE_PASSENGERS',
		'WORLD_VEHICLE_DRIVE_PASSENGERS_LIMITED',
		'WORLD_VEHICLE_DRIVE_SOLO',
		'WORLD_VEHICLE_FIRE_TRUCK',
		'WORLD_VEHICLE_EMPTY',
		'WORLD_VEHICLE_MARIACHI',
		'WORLD_VEHICLE_MECHANIC',
		'WORLD_VEHICLE_MILITARY_PLANES_BIG',
		'WORLD_VEHICLE_MILITARY_PLANES_SMALL',
		'WORLD_VEHICLE_PARK_PARALLEL',
		'WORLD_VEHICLE_PARK_PERPENDICULAR_NOSE_IN',
		'WORLD_VEHICLE_PASSENGER_EXIT',
		'WORLD_VEHICLE_POLICE_BIKE',
		'WORLD_VEHICLE_POLICE_CAR',
		'WORLD_VEHICLE_POLICE',
		'WORLD_VEHICLE_POLICE_NEXT_TO_CAR',
		'WORLD_VEHICLE_QUARRY',
		'WORLD_VEHICLE_SALTON',
		'WORLD_VEHICLE_SALTON_DIRT_BIKE',
		'WORLD_VEHICLE_SECURITY_CAR',
		'WORLD_VEHICLE_STREETRACE',
		'WORLD_VEHICLE_TOURBUS',
		'WORLD_VEHICLE_TOURIST',
		'WORLD_VEHICLE_TANDL',
		'WORLD_VEHICLE_TRACTOR',
		'WORLD_VEHICLE_TRACTOR_BEACH',
		'WORLD_VEHICLE_TRUCK_LOGS',
		'WORLD_VEHICLE_TRUCKS_TRAILERS',
		'WORLD_VEHICLE_DISTANT_EMPTY_GROUND',
		'WORLD_HUMAN_PAPARAZZI'
	}

	for _, v in pairs(scenarios) do
		SetScenarioTypeEnabled(v, false)
	end
end)

CreateThread(function()
	while true do
		wait = 2500

		for ped in EntityManager:enumPeds() do
			if not IsEntityDead(ped) then
				wait = 500
				SetPedDropsWeaponsWhenDead(ped, false)
			end
		end

		Wait(wait)
	end
end)