
Config['concess'] = {
    MenuTitle = {
        MainMenu = "Concessionnaire",
    },
    MenuSubTitle = {
        MainMenu = "Catégories Disponibles",
        VehiclesMenu = "Véhicules",
        OptionsVehicle = "Options du Véhicule"
    },
    
    localisations = {},
    spawn = {},

    Vehicles = {
        Categories = {
            car = {
                { name = 'compacts', label = 'Compacts' },
                { name = 'coupes', label = 'Coupes' },
                { name = 'moto', label = 'Moto' },
                { name = 'muscle', label = 'Muscle' },
                { name = 'off-road', label = 'Off-Road' },
                { name = 'suv', label = 'SUV' },
                { name = 'sedans', label = 'Sedans' },
                { name = 'sports', label = 'Sports' },
                { name = 'sport-classique', label = 'Sport Classique' },
                { name = 'super', label = 'Super' },
                { name = 'vans', label = 'Vans' },
                { name = 'drifts', label = 'Drifts' },
                { name = 'camion', label = 'Camion' },
            },

            boat = {
                { name = 'boat', label = 'Bateaux' },
            },

            aircraft = {
                { name = 'avions', label = 'Avions' },
                { name = 'heli', label = 'Helicoptères' },
            }
        },
    
        Vehicles = {
            car = {
                { cat = 'compacts', model = 'asbo', label = "Abso", price = 16500},
                { cat = 'compacts', model = 'blista', label = "Blista", price = 10000},
                { cat = 'compacts', model = 'brioso', label = "Brioso", price = 23000},
                { cat = 'compacts', model = 'brioso2', label = "Brioso 2", price = 26500},
                { cat = 'compacts', model = 'brioso3', label = "Brioso 3", price = 28000},
                { cat = 'compacts', model = 'club', label = "Club", price = 17000},
                { cat = 'compacts', model = 'dilettante', label = "Dilettante", price = 18000},
                { cat = 'compacts', model = 'kanjo', label = "Kanjo", price = 13000},
                { cat = 'compacts', model = 'issi2', label = "Issi", price = 12000},
                { cat = 'compacts', model = 'panto', label = "Panto", price = 8500},
                { cat = 'compacts', model = 'prairie', label = "Prairie", price = 30000},
                { cat = 'compacts', model = 'rhapsody', label = "Rhapsody", price = 28000},
                { cat = 'compacts', model = 'weevil', label = "Weevil", price = 30000},
        
                { cat = 'coupes', model = 'cogcabrio', label = "Cogcabrio", price = 30000},
                { cat = 'coupes', model = 'exemplar', label = "Exemplar", price = 65000},
                { cat = 'coupes', model = 'f620', label = "F620", price = 100000},
                { cat = 'coupes', model = 'felon', label = "Felon", price = 100000},
                { cat = 'coupes', model = 'felon2', label = "Felon Decapotable", price = 100000},
                { cat = 'coupes', model = 'jackal', label = "Jackal", price = 120000},
                { cat = 'coupes', model = 'oracle', label = "Oracle", price = 90000},
                { cat = 'coupes', model = 'oracle2', label = "Oracle 2", price = 75000},
                { cat = 'coupes', model = 'sentinel', label = "Sentinel", price = 80000},
                { cat = 'coupes', model = 'windsor', label = "Windsor", price = 70000},
                { cat = 'coupes', model = 'windsor2', label = "windsor Decapotable", price = 90000},
                { cat = 'coupes', model = 'zion', label = "Zion", price = 80000},
                { cat = 'coupes', model = 'zion2', label = "Zion Decapotable", price = 120000},
                { cat = 'coupes', model = 'previon', label = "Previon", price = 55000},
        
                { cat = 'moto', model = 'akuma', label = "Akuma", price = 10000},
                { cat = 'moto', model = 'avarus', label = "Avarus", price = 10000},
                { cat = 'moto', model = 'bagger', label = "Bagger", price = 12000},
                { cat = 'moto', model = 'bati', label = "Bati", price = 20000},
                { cat = 'moto', model = 'bf400', label = "BF400", price = 10000},
                { cat = 'moto', model = 'carbonrs', label = "CarbonRS", price = 35000},
                { cat = 'moto', model = 'chimera', label = "Chimera", price = 30000},
                { cat = 'moto', model = 'cliffhanger', label = "Cliffhanger", price = 50000},
                { cat = 'moto', model = 'daemon', label = "Daemon", price = 20000},
                { cat = 'moto', model = 'daemon2', label = "Daemon 2", price = 25000},
                { cat = 'moto', model = 'defiler', label = "Defiler", price = 30000},
                { cat = 'moto', model = 'diablous', label = "Diablous", price = 30000},
                { cat = 'moto', model = 'diablous2', label = "Diablous 2", price = 32000},
                { cat = 'moto', model = 'double', label = "Double", price = 35000},
                { cat = 'moto', model = 'enduro', label = "Enduro", price = 15000},
                { cat = 'moto', model = 'esskey', label = "Esskey", price = 20000},
                { cat = 'moto', model = 'faggio', label = "Faggio", price = 5000},
                { cat = 'moto', model = 'faggio2', label = "Faggio 2", price = 5500},
                { cat = 'moto', model = 'faggio3', label = "Faggio 3", price = 6000},
                { cat = 'moto', model = 'fcr', label = "FCR", price = 30000},
                { cat = 'moto', model = 'fcr2', label = "FCR 2", price = 35000},
                { cat = 'moto', model = 'gargoyle', label = "Gargoyle", price = 20000},
                { cat = 'moto', model = 'hakuchou', label = "Hakuchou", price = 80000},
                { cat = 'moto', model = 'hakuchou2', label = "Hakuchou Drag", price = 100000},
                { cat = 'moto', model = 'hexer', label = "Hexer", price = 40000},
                { cat = 'moto', model = 'innovation', label = "Innovation", price = 50000},
                { cat = 'moto', model = 'lectro', label = "Lectro", price = 60000},
                { cat = 'moto', model = 'manchez', label = "Manchez", price = 8000},
                { cat = 'moto', model = 'manchez2', label = "Manchez de Cayo", price = 10000},
                { cat = 'moto', model = 'manchez3', label = "Manchez 3", price = 12500},
                { cat = 'moto', model = 'powersurge', label = "Powersurge", price = 17500},
                { cat = 'moto', model = 'nemesis', label = "Nemesis", price = 35000},
                { cat = 'moto', model = 'nightblade', label = "Nightblade", price = 35000},
                { cat = 'moto', model = 'ratbike', label = "Ratbike", price = 35000},
                { cat = 'moto', model = 'ruffian', label = "Ruffian", price = 45000},
                { cat = 'moto', model = 'sanchez2', label = "Sanchez", price = 15000},
                { cat = 'moto', model = 'sanctus', label = "Sanctus", price = 150000},
                { cat = 'moto', model = 'sovereign', label = "Sovereign", price = 25000},
                { cat = 'moto', model = 'stryder', label = "Stryder", price = 30000},
                { cat = 'moto', model = 'thrust', label = "Thrust", price = 40000},
                { cat = 'moto', model = 'vader', label = "Vader", price = 45000},
                { cat = 'moto', model = 'vindicator', label = "Vindicator", price = 45000},
                { cat = 'moto', model = 'shinobi', label = "Shinobi", price = 90000},
                { cat = 'moto', model = 'vortex', label = "Vortex", price = 30000},
                { cat = 'moto', model = 'wolfsbane', label = "Wolfsbane", price = 35000},
                { cat = 'moto', model = 'zombiea', label = "Zombiea", price = 40000},
                { cat = 'moto', model = 'zombieb', label = "Zombieb", price = 45000},
        
                
                { cat = 'muscle', model = 'broadway', label = "Broadway", price = 40000},
                { cat = 'muscle', model = 'eudora', label = "Eudora", price = 55000},
                { cat = 'muscle', model = 'blade', label = "Blade", price = 50000},
                { cat = 'muscle', model = 'buccaneer', label = "Buccaneer", price = 50000},
                { cat = 'muscle', model = 'buccaneer2', label = "Buccaneer 2", price = 55000},
                { cat = 'muscle', model = 'chino', label = "Chino", price = 65000},
                { cat = 'muscle', model = 'chino2', label = "Chino 2", price = 70000},
                { cat = 'muscle', model = 'clique', label = "Clique", price = 40000},
                { cat = 'muscle', model = 'coquette3', label = "Coquette 3", price = 53000},
                { cat = 'muscle', model = 'deviant', label = "Deviant", price = 60000},
                { cat = 'muscle', model = 'dominator', label = "Dominator", price = 50000},
                { cat = 'muscle', model = 'dominator3', label = "Dominator 3", price = 60000},
                { cat = 'muscle', model = 'dominator7', label = "Dominator 7", price = 70000},
                { cat = 'muscle', model = 'dukes', label = "Dukes", price = 80000},
                { cat = 'muscle', model = 'faction', label = "Faction", price = 50000},
                { cat = 'muscle', model = 'faction2', label = "Faction 2", price = 60000},
                { cat = 'muscle', model = 'faction3', label = "Faction 3", price = 70000},
                { cat = 'muscle', model = 'ellie', label = "Ellie", price = 50000},
                { cat = 'muscle', model = 'gauntlet', label = "Gauntlet", price = 30000},
                { cat = 'muscle', model = 'gauntlet3', label = "Gauntlet 3", price = 55000},
                { cat = 'muscle', model = 'gauntlet4', label = "Gauntlet 4", price = 58000},
                { cat = 'muscle', model = 'gauntlet5', label = "Gauntlet 5", price = 50000},
                { cat = 'muscle', model = 'greenwood', label = "Greenwood", price = 50000},
                { cat = 'muscle', model = 'hermes', label = "Hermes", price = 100000},
                { cat = 'muscle', model = 'hotknife', label = "Hotknife", price = 85000},
                { cat = 'muscle', model = 'hustler', label = "Hustler", price = 90000},
                { cat = 'muscle', model = 'lurcher', label = "Lurcher", price = 60000},
                { cat = 'muscle', model = 'moonbeam', label = "Moonbeam", price = 80000},
                { cat = 'muscle', model = 'moonbeam2', label = "Moonbeam 2", price = 75000},
                { cat = 'muscle', model = 'nightshade', label = "Nightshade", price = 280000},
                { cat = 'muscle', model = 'peyote2', label = "Peyote 2", price = 70000},
                { cat = 'muscle', model = 'phoenix', label = "Phoenix", price = 60000},
                { cat = 'muscle', model = 'picador', label = "Picador", price = 70000},
                { cat = 'muscle', model = 'ratloader2', label = "Ratloader", price = 125000},
                { cat = 'muscle', model = 'ruiner', label = "Ruiner", price = 120000},
                { cat = 'muscle', model = 'ruiner4', label = "Ruiner 4", price = 125000},
                { cat = 'muscle', model = 'sabregt', label = "SabreGT", price = 40000},
                { cat = 'muscle', model = 'slamvan', label = "Slamvan", price = 80000},
                { cat = 'muscle', model = 'slamvan2', label = "Slamvan 2", price = 85000},
                { cat = 'muscle', model = 'slamvan3', label = "Slamvan 3", price = 90000},
                { cat = 'muscle', model = 'tahoma', label = "Tahoma", price = 30000},
                { cat = 'muscle', model = 'stalion', label = "Stalion", price = 39000},
                { cat = 'muscle', model = 'tampa', label = "Tampa", price = 40000},
                { cat = 'muscle', model = 'tulip', label = "Tulip", price = 55000},
                { cat = 'muscle', model = 'tulip2', label = "Tulip 2", price = 80000},
                { cat = 'muscle', model = 'vamos', label = "Vamos", price = 50000},
                { cat = 'muscle', model = 'vigero', label = "Vigero", price = 40000},
                { cat = 'muscle', model = 'vigero2', label = "Vigero 2", price = 65000},
                { cat = 'muscle', model = 'virgo', label = "Virgo", price = 30000},
                { cat = 'muscle', model = 'virgo2', label = "Virgo 2", price = 35000},
                { cat = 'muscle', model = 'virgo3', label = "Virgo 3", price = 45000},
                { cat = 'muscle', model = 'voodoo', label = "Voodoo", price = 90000},
                { cat = 'muscle', model = 'yosemite', label = "Yosemite", price = 60000},
                { cat = 'muscle', model = 'yosemite2', label = "Yosemite 2", price = 80000},
                { cat = 'muscle', model = 'yosemite3', label = "Yosemite 3", price = 100000},
                { cat = 'muscle', model = 'weevil2', label = "Weevil 2", price = 120000},
        
                { cat = 'off-road', model = 'bfinjection', label = "BFInjection", price = 35000},
                { cat = 'off-road', model = 'bifta', label = "Bifta", price = 45000},
                { cat = 'off-road', model = 'blazer', label = "Blazer", price = 40000},
                { cat = 'off-road', model = 'blazer3', label = "Blazer 3", price = 50000},
                { cat = 'off-road', model = 'blazer4', label = "Blazer 4", price = 55000},
                { cat = 'off-road', model = 'bodhi2', label = "Bodhi", price = 55000},
                { cat = 'off-road', model = 'brawler', label = "Brawler", price = 55000},
                { cat = 'off-road', model = 'caracara2', label = "Caracara", price = 145000},
                { cat = 'off-road', model = 'dloader', label = "Dloader", price = 110000},
                { cat = 'off-road', model = 'draugur', label = "Draugur", price = 100000},
                { cat = 'off-road', model = 'dubsta3', label = "Dubsta3", price = 100000},
                { cat = 'off-road', model = 'everon', label = "Everon", price = 75000},
                { cat = 'off-road', model = 'freecrawler', label = "Freecrawler", price = 90000},
                { cat = 'off-road', model = 'hellion', label = "Hellion", price = 100000},
                { cat = 'off-road', model = 'kalahari', label = "Kalahari", price = 100000},
                { cat = 'off-road', model = 'kamacho', label = "Kamacho", price = 120000},
                { cat = 'off-road', model = 'mesa3', label = "Mesa 3", price = 110000},
                { cat = 'off-road', model = 'outlaw', label = "Outlaw", price = 105000},
                { cat = 'off-road', model = 'rancherxl', label = "RancherXL", price = 110000},
                { cat = 'off-road', model = 'rebel2', label = "Rebel 2", price = 115000},
                { cat = 'off-road', model = 'riata', label = "Riata", price = 120000},
                { cat = 'off-road', model = 'sandking', label = "Sandking", price = 150000},
                { cat = 'off-road', model = 'sandking2', label = "Sandking 2", price = 160000},
                { cat = 'off-road', model = 'trophytruck', label = "Trophytruck", price = 150000},
                { cat = 'off-road', model = 'trophytruck2', label = "Trophytruck 2", price = 155000},
                { cat = 'off-road', model = 'vagrant', label = "Vagrant", price = 155000},
            
                { cat = 'suv', model = 'baller', label = "Baller", price = 80000},
                { cat = 'suv', model = 'baller2', label = "Baller 2", price = 90000},
                { cat = 'suv', model = 'baller7', label = "Baller 7", price = 100000},
                { cat = 'suv', model = 'baller8', label = "Baller 8", price = 150000},
                { cat = 'suv', model = 'baller4', label = "Baller Sport", price = 200000},
                { cat = 'suv', model = 'bjxl', label = "BJXL", price = 75000},
                { cat = 'suv', model = 'cavalcade', label = "Cavalcade", price = 160000},
                { cat = 'suv', model = 'cavalcade2', label = "Cavalcade 2", price = 195000},
                { cat = 'suv', model = 'contender', label = "Contender", price = 160000},
                { cat = 'suv', model = 'dubsta', label = "Dubsta", price = 150000},
                { cat = 'suv', model = 'dubsta2', label = "Dubsta Sport", price = 255000},
                { cat = 'suv', model = 'fq2', label = "FQ2", price = 195000},
                { cat = 'suv', model = 'granger', label = "Granger", price = 170000},
                { cat = 'suv', model = 'gresley', label = "Gresley", price = 175000},
                { cat = 'suv', model = 'habanero', label = "Habanero", price = 180000},
                { cat = 'suv', model = 'huntley', label = "Huntley", price = 175000},
                { cat = 'suv', model = 'landstalker', label = "Landstalker", price = 150000},
                { cat = 'suv', model = 'landstalker2', label = "Landstalker 2", price = 220000},
                { cat = 'suv', model = 'mesa', label = "Mesa", price = 175000},
                { cat = 'suv', model = 'novak', label = "Novak", price = 190000},
                { cat = 'suv', model = 'patriot', label = "Patriot", price = 160000},
                { cat = 'suv', model = 'radi', label = "Radi", price = 190000},
                { cat = 'suv', model = 'rebla', label = "Rebla", price =130000},
                { cat = 'suv', model = 'rocoto', label = "Rocoto", price = 198000},
                { cat = 'suv', model = 'seminole', label = "Seminole", price = 140000},
                { cat = 'suv', model = 'seminole2', label = "Seminole 2", price = 245000},
                { cat = 'suv', model = 'serrano', label = "Serrano", price = 255000},
                { cat = 'suv', model = 'toros', label = "Toros", price = 400000},
                { cat = 'suv', model = 'xls', label = "XLS", price = 500000},
                { cat = 'suv', model = 'issi8', label = "Issi 8", price = 380000},
        
                { cat = 'sedans', model = 'asea', label = "Asea", price = 10000},
                { cat = 'sedans', model = 'asterope', label = "Asterope", price = 10000},
                { cat = 'sedans', model = 'cog55', label = "Cog55", price = 20000},
                { cat = 'sedans', model = 'cognoscenti', label = "Cognoscenti", price = 20000},
                { cat = 'sedans', model = 'emperor', label = "Emperor", price = 11000},
                { cat = 'sedans', model = 'fugitive', label = "Fugitive", price = 16000},
                { cat = 'sedans', model = 'glendale', label = "Glendale", price = 10000},
                { cat = 'sedans', model = 'glendale2', label = "Glendale 2", price = 12000},
                { cat = 'sedans', model = 'ingot', label = "Ingot", price = 25000},
                { cat = 'sedans', model = 'intruder', label = "Intruder", price = 17000},
                { cat = 'sedans', model = 'premier', label = "Premier", price = 17000},
                { cat = 'sedans', model = 'primo', label = "Primo", price = 20000},
                { cat = 'sedans', model = 'primo2', label = "Primo Custom", price = 25000},
                { cat = 'sedans', model = 'regina', label = "Regina", price = 35000},
                { cat = 'sedans', model = 'stafford', label = "Stafford", price = 25000},
                { cat = 'sedans', model = 'stanier', label = "Stanier", price = 40000},
                { cat = 'sedans', model = 'stratum', label = "Stratum", price = 30000},
                { cat = 'sedans', model = 'superd', label = "Superd", price = 50000},
                { cat = 'sedans', model = 'surge', label = "Surge", price = 25000},
                { cat = 'sedans', model = 'tailgater', label = "Tailgater", price = 25000},
                { cat = 'sedans', model = 'tailgater2', label = "Tailgater S", price = 30000},
                { cat = 'sedans', model = 'warrener', label = "Warrener", price = 40000},
                { cat = 'sedans', model = 'washington', label = "Washington", price = 50000},
                { cat = 'sedans', model = 'buffalo4', label = "Buffalo 4", price = 550000},
        
                { cat = 'sports', model = 'alpha', label = "Alpha", price = 115000},
                { cat = 'sports', model = 'banshee', label = "Banshee", price = 110000},
                { cat = 'sports', model = 'bestiagts', label = "Bestiagts", price = 110000},
                { cat = 'sports', model = 'blista2', label = "Blista 2", price = 108000},
                { cat = 'sports', model = 'buffalo', label = "Buffalo", price = 120000},
                { cat = 'sports', model = 'buffalo2', label = "Buffalo S", price = 180000},
                { cat = 'sports', model = 'carbonizzare', label = "Carbonizzare", price = 110000},
                { cat = 'sports', model = 'calico', label = "Calico", price = 300000},
                { cat = 'sports', model = 'comet2', label = "Comet 2", price = 400000},
                { cat = 'sports', model = 'comet3', label = "Comet 3", price = 500000},
                { cat = 'sports', model = 'comet5', label = "Comet 5", price = 600000},
                { cat = 'sports', model = 'comet6', label = "Comet 6", price = 700000},
                { cat = 'sports', model = 'coquette', label = "Coquette", price = 270000},
                { cat = 'sports', model = 'coquette4', label = "Coquette 4", price = 280000},
                { cat = 'sports', model = 'corsita', label = "Corsita", price = 370000},
                { cat = 'sports', model = 'cypher', label = "Cypher", price = 150000},
                { cat = 'sports', model = 'drafter', label = "Drafter", price = 300000},
                { cat = 'sports', model = 'deveste', label = "Deveste", price = 110000},
                { cat = 'sports', model = 'elegy', label = "Elegy Retro Custom", price = 110000},
                { cat = 'sports', model = 'elegy2', label = "Elegy RH8", price = 135000},
                { cat = 'sports', model = 'euros', label = "Euros", price = 130000},
                { cat = 'sports', model = 'feltzer2', label = "Feler 2", price = 140000},
                { cat = 'sports', model = 'flashgt', label = "FlashGT", price = 295000},
                { cat = 'sports', model = 'furoregt', label = "FuroreGT", price = 375000},
                { cat = 'sports', model = 'fusilade', label = "Fusilade", price = 265000},
                { cat = 'sports', model = 'futo', label = "Futo", price = 100000},
                { cat = 'sports', model = 'futo2', label = "Futo 2", price = 150000},
                { cat = 'sports', model = 'gb200', label = "GB200", price = 210000},
                { cat = 'sports', model = 'growler', label = "Growler", price = 230000},
                { cat = 'sports', model = 'hotring', label = "Hotring", price = 175000},
                { cat = 'sports', model = 'komoda', label = "Komoda", price = 240000},
                { cat = 'sports', model = 'imorgon', label = "Imorgon", price = 185000},
                { cat = 'sports', model = 'issi7', label = "Issi 7", price = 195000},
                { cat = 'sports', model = 'italigto', label = "ItaliGTO", price = 450000},
                { cat = 'sports', model = 'italirsx', label = "ItaliRSX", price = 460000},
                { cat = 'sports', model = 'jugular', label = "Jugular", price = 200000},
                { cat = 'sports', model = 'jester', label = "Jester", price = 250000},
                { cat = 'sports', model = 'jester3', label = "Jester 3", price = 370000},
                { cat = 'sports', model = 'jester4', label = "Jester 4", price = 185000},
                { cat = 'sports', model = 'khamelion', label = "Khamelion", price = 240000},
                { cat = 'sports', model = 'kuruma', label = "Kuruma", price = 190000},
                { cat = 'sports', model = 'locust', label = "Locust", price = 150000},
                { cat = 'sports', model = 'lynx', label = "Line", price = 270000},
                { cat = 'sports', model = 'massacro', label = "Massacro", price = 230000},
                { cat = 'sports', model = 'neo', label = "Neo", price = 100000},
                { cat = 'sports', model = 'neon', label = "Neon", price = 160000},
                { cat = 'sports', model = 'revolter', label = "Revolter", price = 350000},
                { cat = 'sports', model = 'ninef', label = "Ninef", price = 110000},
                { cat = 'sports', model = 'ninef2', label = "Ninef 2", price = 120000},
                { cat = 'sports', model = 'omnis', label = "Omnis", price = 100000},
                { cat = 'sports', model = 'paragon', label = "Paragon", price = 80000},
                { cat = 'sports', model = 'pariah', label = "pariah", price = 40000},
                { cat = 'sports', model = 'penumbra', label = "penumbra", price = 20000},
                { cat = 'sports', model = 'penumbra2', label = "Penumbra 2", price = 25000},
                { cat = 'sports', model = 'raiden', label = "Raiden", price = 230000},
                { cat = 'sports', model = 'rapidgt', label = "RapidGT", price = 170000},
                { cat = 'sports', model = 'raptor', label = "Raptor", price = 110000},
                { cat = 'sports', model = 'remus', label = "Remus", price = 140000},
                { cat = 'sports', model = 'rhinehart', label = "Rhinehart", price = 250000},
                { cat = 'sports', model = 'rt3000', label = "RT3000", price = 170000},
                { cat = 'sports', model = 'ruston', label = "Ruston", price = 150000},
                { cat = 'sports', model = 'schafter2', label = "Schafter", price = 170000},
                { cat = 'sports', model = 'schafter3', label = "Schafter  2", price = 180000},
                { cat = 'sports', model = 'schlagen', label = "Schlagen", price = 210000},
                { cat = 'sports', model = 'schwarzer', label = "Schwarzer", price = 185000},
                { cat = 'sports', model = 'sentinel3', label = "Sentinel 3", price = 25000},
                { cat = 'sports', model = 'sentinel4', label = "Sentinel 4", price = 30000},
                { cat = 'sports', model = 'seven70', label = "Seven 70", price = 200000},
                { cat = 'sports', model = 'sm722', label = "SM722", price = 230000},
                { cat = 'sports', model = 'specter', label = "Specter", price = 170000},
                { cat = 'sports', model = 'specter2', label = "Specter 2", price = 180000},
                { cat = 'sports', model = 'streiter', label = "Streiter", price = 100000},
                { cat = 'sports', model = 'sugoi', label = "Sugoi", price = 30000},
                { cat = 'sports', model = 'sultan', label = "Sultan", price = 30000},
                { cat = 'sports', model = 'sultan2', label = "Sultan 2", price = 50000},
                { cat = 'sports', model = 'sultan3', label = "Sultan 3", price = 80000},
                { cat = 'sports', model = 'surano', label = "Surano", price = 30000},
                { cat = 'sports', model = 'tampa2', label = "Tampa 2", price = 30000},
                { cat = 'sports', model = 'tropos', label = "Tropos", price = 170000},
                { cat = 'sports', model = 'vectre', label = "Vectre", price = 190000},
                { cat = 'sports', model = 'verlierer2', label = "Verlierer2", price = 120000},
                { cat = 'sports', model = 'vstr', label = "VSTR", price = 210000},
                { cat = 'sports', model = 'zr350', label = "ZR350", price = 230000},
                { cat = 'sports', model = 'everon2', label = "Everon 2", price = 130000},
                { cat = 'sports', model = 'panthere', label = "Panthere", price = 150000},
                { cat = 'sports', model = 'r300', label = "R300", price = 135000},
                
                { cat = 'sport-classique', model = 'btype', label = "BType", price = 225000},
                { cat = 'sport-classique', model = 'btype2', label = "BType 2", price = 250000},
                { cat = 'sport-classique', model = 'btype3', label = "BType 3", price = 260000},
                { cat = 'sport-classique', model = 'casco', label = "Casco", price = 210000},
                { cat = 'sport-classique', model = 'cheburek', label = "Cheburek", price = 180000},
                { cat = 'sport-classique', model = 'cheetah2', label = "Cheetah 2", price = 230000},
                { cat = 'sport-classique', model = 'coquette2', label = "Coquette 2", price = 240000},
                { cat = 'sport-classique', model = 'dynasty', label = "Dynasty", price = 140000},
                { cat = 'sport-classique', model = 'fagaloa', label = "Fagaloa", price = 100000},
                { cat = 'sport-classique', model = 'feltzer3', label = "Feler3", price = 140000},
                { cat = 'sport-classique', model = 'gt500', label = "GT500", price = 195000},
                { cat = 'sport-classique', model = 'infernus2', label = "Infernus 2", price = 220000},
                { cat = 'sport-classique', model = 'mamba', label = "Mamba", price = 210000},
                { cat = 'sport-classique', model = 'manana', label = "Manana", price = 90000},
                { cat = 'sport-classique', model = 'manana2', label = "Manana 2", price = 100000},
                { cat = 'sport-classique', model = 'michelli', label = "Michelli", price = 110000},
                { cat = 'sport-classique', model = 'monroe', label = "Monroe", price = 210000},
                { cat = 'sport-classique', model = 'nebula', label = "Nebula", price = 100000},
                { cat = 'sport-classique', model = 'peyote', label = "Peyote", price = 90000},
                { cat = 'sport-classique', model = 'peyote3', label = "Peyote 3", price = 95000},
                { cat = 'sport-classique', model = 'pigalle', label = "Pigalle", price = 100000},
                { cat = 'sport-classique', model = 'rapidgt3', label = "RapiGT 3", price = 140000},
                { cat = 'sport-classique', model = 'retinue', label = "Retinue", price = 130000},
                { cat = 'sport-classique', model = 'retinue2', label = "Retinue 2", price = 140000},
                { cat = 'sport-classique', model = 'stinger', label = "Stinger", price = 160000},
                { cat = 'sport-classique', model = 'stingergt', label = "StingerGT", price = 170000},
                { cat = 'sport-classique', model = 'swinger', label = "Swinger", price = 150000},
                { cat = 'sport-classique', model = 'torero', label = "Torero", price = 200000},
                { cat = 'sport-classique', model = 'tornado', label = "Tornado", price = 90000},
                { cat = 'sport-classique', model = 'tornado2', label = "Tornado 2", price = 95000},
                { cat = 'sport-classique', model = 'tornado5', label = "Tornado 5", price = 100000},
                { cat = 'sport-classique', model = 'turismo2', label = "Turismo 2", price = 350000},
                { cat = 'sport-classique', model = 'z190', label = "Z190", price = 220000},
                { cat = 'sport-classique', model = 'zion3', label = "Zion 3", price = 180000},
                { cat = 'sport-classique', model = 'ztype', label = "ZType", price = 200000},
        
                { cat = 'super', model = 'adder', label = "Adder", price = 1750000},
                { cat = 'super', model = 'autarch', label = "Autarch", price = 1800000},
                { cat = 'super', model = 'banshee2', label = "Banshee 2", price = 1550000},
                { cat = 'super', model = 'bullet', label = "Bullet", price = 1550000},
                { cat = 'super', model = 'cheetah', label = "Cheetah", price = 1650000},
                { cat = 'super', model = 'cyclone', label = "Cyclone", price = 1500000},
                { cat = 'super', model = 'entity2', label = "Entity 2", price = 1850000},
                { cat = 'super', model = 'entity3', label = "Entity 3", price = 1855000},
                { cat = 'super', model = 'entityxf', label = "EntityXF", price = 1800000},
                { cat = 'super', model = 'emerus', label = "Emerus", price = 1850000},
                { cat = 'super', model = 'fmj', label = "FMJ", price = 1750000},
                { cat = 'super', model = 'furia', label = "Furia", price = 1700000},
                { cat = 'super', model = 'gp1', label = "GP1", price = 1550000},
                { cat = 'super', model = 'ignus', label = "Ignus", price = 1850000},
                { cat = 'super', model = 'infernus', label = "Infernus", price = 1550000},
                { cat = 'super', model = 'italigtb', label = "ItaliGTB", price = 1600000},
                { cat = 'super', model = 'italigtb2', label = "ItaliGTB 2", price = 1620000},
                { cat = 'super', model = 'krieger', label = "Krieger", price = 1900000},
                { cat = 'super', model = 'le7b', label = "LE7B", price = 1600000},
                { cat = 'super', model = 'lm87', label = "LM87", price = 1585000},
                { cat = 'super', model = 'nero', label = "Nero", price = 1700000},
                { cat = 'super', model = 'nero2', label = "Nero 2", price = 1750000},
                { cat = 'super', model = 'osiris', label = "Osiris", price = 1800000},
                { cat = 'super', model = 'penetrator', label = "Penetrator", price = 1750000},
                { cat = 'super', model = 'pfister811', label = "Pfister811", price = 1750000},
                { cat = 'super', model = 'prototipo', label = "Prototipo", price = 1850000},
                { cat = 'super', model = 'reaper', label = "Reaper", price = 1900000},
                { cat = 'super', model = 's80', label = "S80", price = 1800000},
                { cat = 'super', model = 'sc1', label = "SC1", price = 1750000},
                { cat = 'super', model = 'sheava', label = "Sheava", price = 1800000},
                { cat = 'super', model = 'sultanrs', label = "SultanRS", price = 1000000},
                { cat = 'super', model = 't20', label = "T20", price = 1950000},
                { cat = 'super', model = 'taipan', label = "Taipan", price = 1825000},
                { cat = 'super', model = 'tempesta', label = "Tempesta", price = 1800000},
                { cat = 'super', model = 'thrax', label = "Thrax", price = 1850000},
                { cat = 'super', model = 'tigon', label = "Tigon", price = 1875000},
                { cat = 'super', model = 'tenf', label = "Tenf", price = 1850000},
                { cat = 'super', model = 'tenf2', label = "Tenf 2", price = 1875000},
                { cat = 'super', model = 'torero2', label = "Torero 2", price = 1620000},
                { cat = 'super', model = 'turismor', label = "TurismoR", price = 1750000},
                { cat = 'super', model = 'tyrant', label = "Tyrant", price = 1875000},
                { cat = 'super', model = 'tyrus', label = "Tyrus", price = 1825000},
                { cat = 'super', model = 'vacca', label = "Vacca", price = 1800000},
                { cat = 'super', model = 'vagner', label = "Vagner", price = 1900000},
                { cat = 'super', model = 'visione', label = "Visione", price = 1850000},
                { cat = 'super', model = 'voltic', label = "Voltic", price = 1800000},
                { cat = 'super', model = 'xa21', label = "XA21", price = 1850000},
                { cat = 'super', model = 'zentorno', label = "Zentorno", price = 2000000},
                { cat = 'super', model = 'zorrusso', label = "Zorrusso", price = 2850000},
                { cat = 'super', model = 'virtue', label = "Virtue", price = 2855000},
                { cat = 'super', model = 'tezeract', label = "Tezeract", price = 2500000},
                { cat = 'super', model = 'deity', label = "Deity", price = 2250000},
        
                { cat = 'vans', model = 'bison', label = "Bison", price = 75000},
                { cat = 'vans', model = 'bison2', label = "Bison 2", price = 80000},
                { cat = 'vans', model = 'bobcatxl', label = "Bobcatxl", price = 85000},
                { cat = 'vans', model = 'burrito3', label = "Burrito", price = 70000},
                { cat = 'vans', model = 'camper', label = "Camper", price = 90000},
                { cat = 'vans', model = 'gburrito', label = "GBurrito", price = 100000},
                { cat = 'vans', model = 'gburrito2', label = "GBurrito 2", price = 110000},
                { cat = 'vans', model = 'journey', label = "Journey", price = 70000},
                { cat = 'vans', model = 'journey2', label = "Journey 2", price = 75000},
                { cat = 'vans', model = 'minivan', label = "Minivan", price = 90000},
                { cat = 'vans', model = 'minivan2', label = "Minivan 2", price = 95000},
                { cat = 'vans', model = 'paradise', label = "Paradise", price = 80000},
                { cat = 'vans', model = 'pony', label = "Pony", price = 80000},
                { cat = 'vans', model = 'rumpo', label = "Rumpo", price = 80000},
                { cat = 'vans', model = 'rumpo3', label = "Rumpo 3", price = 90000},
                { cat = 'vans', model = 'speedo', label = "Speedo", price = 100000},
                { cat = 'vans', model = 'speedo2', label = "Speedo Clown", price = 140000},
                { cat = 'vans', model = 'surfer', label = "Surfer", price = 100000},
                { cat = 'vans', model = 'surfer2', label = "Surfer 2", price = 50000},
                { cat = 'vans', model = 'surfer3', label = "Surfer 3", price = 70000},
                { cat = 'vans', model = 'youga', label = "Youga", price = 90000},
                { cat = 'vans', model = 'youga2', label = "Youga 2", price = 92500},
                { cat = 'vans', model = 'youga3', label = "Youga 3", price = 95000},        
                { cat = 'vans', model = 'cavalcade3', label = "CavalCade 3", price = 150000},        
                
                { cat = 'drifts', model = 'driftfuto',     label = "Drift Futo",     price = 1415000 },
                { cat = 'drifts', model = 'driftfr36',     label = "Drift FR36",     price = 1470000 },
                { cat = 'drifts', model = 'driftremus',    label = "Drift Remus",    price = 1550000 },
                { cat = 'drifts', model = 'drifteuros',    label = "Drift Euros",    price = 1665000 },
                { cat = 'drifts', model = 'driftzr350',    label = "Drift ZR350",    price = 1780000 },
                { cat = 'drifts', model = 'driftyosemite', label = "Drift Yosemite", price = 1800000 },
                { cat = 'drifts', model = 'driftjester',   label = "Drift Jester",   price = 1142500 },
                { cat = 'drifts', model = 'drifttampa',    label = "Drift Tampa",    price = 1950000 },

                { cat = 'camion', model = 'mule',    label = "Mule",    price = 750000 },
                { cat = 'camion', model = 'mule2',    label = "Mule 2",    price = 1000000 },
                { cat = 'camion', model = 'mule3',    label = "Mule 3",    price = 2000000 },
                { cat = 'camion', model = 'mule4',    label = "Mule 4",    price = 3000000 },
                
            },

            boat = {
                { cat = 'boat', model = 'dinghy', label = "Dinghy", price = 1500000},
                { cat = 'boat', model = 'jetmax', label = "Jetmax", price = 1000000},
                { cat = 'boat', model = 'marquis', label = "Marquis", price = 2500000},
                { cat = 'boat', model = 'seashark3', label = "Jet Ski", price = 500000},
                { cat = 'boat', model = 'speeder', label = "Speeder", price = 1500000},
                { cat = 'boat', model = 'squalo', label = "Squalo", price = 750000},
                { cat = 'boat', model = 'suntrap', label = "Suntrap", price = 650000},
                { cat = 'boat', model = 'toro', label = "Toro", price = 1500000},
                { cat = 'boat', model = 'tropic', label = "Tropic", price = 1000000},
                { cat = 'boat', model = 'longfin', label = "Longfin", price = 2000000},
            },

            aircraft = {
                { cat = 'avions', model = 'frogger', label = "Frogger", price = 4500000},
                { cat = 'avions', model = 'cuban800', label = "Cuban 800", price = 3500000},
                { cat = 'avions', model = 'dodo', label = "Dodo", price = 4500000},
                { cat = 'avions', model = 'duster', label = "Duster", price = 2500000},
                { cat = 'avions', model = 'howard', label = "Howard", price = 3500000},
                { cat = 'avions', model = 'luxor', label = "Luxor", price = 20000000},
                { cat = 'avions', model = 'luxor2', label = "lUxor 2", price = 30000000},
                { cat = 'avions', model = 'mammatus', label = "Mammatus", price = 4500000},
                { cat = 'avions', model = 'microlight', label = "Microlight", price = 1500000},
                { cat = 'avions', model = 'nimbus', label = "Nimbus", price = 8500000},
                { cat = 'avions', model = 'seabreeze', label = "Seabreeze", price = 6500000},
                { cat = 'avions', model = 'stunt', label = "Stunt", price = 4500000},
                { cat = 'avions', model = 'velum', label = "Velum", price = 5500000},
                { cat = 'avions', model = 'velum2', label = "Velum 2", price = 5000000},
                { cat = 'avions', model = 'vestra', label = "Vestra", price = 3500000},

                { cat = 'heli', model = 'buzzard2', label = "Buzzard", price = 6500000},
                { cat = 'heli', model = 'frogger', label = "Frogger", price = 4500000},
                { cat = 'heli', model = 'frogger2', label = "Frogger 2", price = 4700000},
                { cat = 'heli', model = 'havok', label = "Havok", price = 3000000},
                { cat = 'heli', model = 'maverick', label = "Maverick", price = 4000000},
                { cat = 'heli', model = 'supervolito', label = "Supervolito", price = 7000000},
                { cat = 'heli', model = 'supervolito2', label = "Supervolito 2", price = 7500000},
                { cat = 'heli', model = 'swift', label = "Swift", price = 8000000},
                { cat = 'heli', model = 'swift2', label = "Swift 2", price = 8500000},
                { cat = 'heli', model = 'volatus', label = "Volatus", price = 9000000},
                { cat = 'heli', model = 'seasparrow2', label = "Seasparrow", price = 4500000},
            }
        }
    }
}

if Config:gabz() then
    Config['concess'].localisations = {
        { 
            type = 'car',
            pos = vector3(-33.7, -1096.9, 27.3),
            sprite = 326,
            color = 0,
            label = "Concessionnaire | Voitures"
        },
        { 
            type = 'boat',
            pos = vector3(-815.6, -1346.1, 5.1),
            sprite = 455,
            color = 0,
            label = "Concessionnaire | Bateaux"
        },
        { 
            type = 'aircraft',
            pos = vector3(-941.5, -2954.5, 13.9),
            sprite = 307,
            color = 0,
            label = "Concessionnaire | Avions"
        },
    }
    Config['concess'].spawn = {
        car = {
            pos = vector3(-23.5, -1094.4, 27.3),
            head = -20.0,
            camPos = vector3(-27.1, -1097.1, 27.3),
            camROTX = -30.0,
            camFOV = 80.0
        },
        
        boat = {
            pos = vector3(-776.1, -1412, 0),
            head = 255.0,
            camPos = vector3(-768.6, -1401.4, 3.8),
            camROTX = 145.0,
            camFOV = 30.0
        },

        aircraft = {
            pos = vector3(-957.2, -2963, 13.9),
            head = 255.0,
            camPos = vector3(-965.8, -2958.4, 17),
            camROTX = -115.0,
            camFOV = 80.0
        }
    }
else
    Config['concess'].localisations = {
        { 
            type = 'car',
            pos = vector3(-42.1, -1103.8, 26.4),
            sprite = 326,
            color = 0,
            label = "Concessionnaire | Voitures"
        },
        { 
            type = 'boat',
            pos = vector3(-815.6, -1346.1, 5.1),
            sprite = 455,
            color = 0,
            label = "Concessionnaire | Bateaux"
        },
        { 
            type = 'aircraft',
            pos = vector3(-941.5, -2954.5, 13.9),
            sprite = 307,
            color = 0,
            label = "Concessionnaire | Avions"
        },
    }
    Config['concess'].spawn = {
        car = {
            pos = vector3(-31.9, -1090.7, 26.4),
            head = -20.0,
            camPos = vector3(-28.6, -1092.8, 27.4),
            camROTX = 50.0,
            camFOV = 80.0
        },
        
        boat = {
            pos = vector3(-776.1, -1412, 0),
            head = 255.0,
            camPos = vector3(-768.6, -1401.4, 3.8),
            camROTX = 145.0,
            camFOV = 30.0
        },

        aircraft = {
            pos = vector3(-957.2, -2963, 13.9),
            head = 255.0,
            camPos = vector3(-965.8, -2958.4, 17),
            camROTX = -115.0,
            camFOV = 80.0
        }
    }
end