CreateThread(function()
    SetDiscordAppId(1310685465736908861)
    SetDiscordRichPresenceAsset('adistre_officeil_png') 
    SetDiscordRichPresenceAssetText('Adistra')
    SetDiscordRichPresenceAssetSmall('adistre_officeil_png')
    SetDiscordRichPresenceAssetSmallText('discord.gg/adistrarp')
    SetDiscordRichPresenceAction(0, "Rejoindre le discord", "https://discord.gg/adistrarp")
    SetDiscordRichPresenceAction(1, "Rejoindre AdistraRP", "https://cfx.re/join/zzy3x")
    SetRichPresence(("[%s] - %s"):format(GetPlayerServerId(PlayerId()), GetPlayerName(PlayerId())))
end)