---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Stitchdev.
--- DateTime: 22/10/2024 15:25
---

local display = false

RegisterCommand("tablet", function()
    SetDisplay(not display)
end)

function SetDisplay(bool)
    display = bool
    SetNuiFocus(bool, bool)
    SendNUIMessage({
        type = "ui",
        status = bool
    })
end

RegisterNUICallback("appClick", function(data)
    print("App clicked: " .. data.app)
    if data.app == "Documents" then
        print("Ouverture des documents")
        TriggerEvent("tablet:openDocuments")
    elseif data.app == "My Files" then
        -- Action pour My Files
        print("Ouverture des fichiers")
        TriggerEvent("tablet:openFiles")
    end
end)

-- Callback pour fermer
RegisterNUICallback("exit", function(data)
    SetDisplay(false)
end)